name: Build and Deploy Astro to GitHub Pages

on:
  push:
    branches:
      - develop  # Build on develop
      - main     # Build and deploy on main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Astro site
        run: |
          rm -rf dist/*
          npm run build

      - name: Save dist/ as artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Deploy only if build succeeds
    if: github.ref == 'refs/heads/main'  # Deploy only on main branch
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: github-pages

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          path: dist/
